import 'package:folio/generated/app_localizations.dart';

const bool estBuildPlayStore = String.fromEnvironment('STORE') == 'play';

String statusLabel(String dbValue, AppLocalizations l10n) => switch (dbValue) {
  'À lire' => l10n.statusToRead,
  'En cours' => l10n.statusReading,
  'Terminé' => l10n.statusFinished,
  'Abandonné' => l10n.statusDropped,
  _ => dbValue,
};

String genreLabel(String genre, AppLocalizations l10n) => switch (genre) {
  'Action'        => l10n.genreAction,
  'Adventure'     => l10n.genreAdventure,
  'Martial Arts'  => l10n.genreMartialArts,
  'Sports'        => l10n.genreSports,
  'Romance'       => l10n.genreRomance,
  'Comedy'        => l10n.genreComedy,
  'Drama'         => l10n.genreDrama,
  'Slice of Life' => l10n.genreSliceOfLife,
  'Mystery'       => l10n.genreMystery,
  'Thriller'      => l10n.genreThriller,
  'Horror'        => l10n.genreHorror,
  'Psychological' => l10n.genrePsychological,
  'Fantasy'       => l10n.genreFantasy,
  'Sci-Fi'        => l10n.genreSciFi,
  'Isekai'        => l10n.genreIsekai,
  'Supernatural'  => l10n.genreSupernatural,
  'Mecha'         => l10n.genreMecha,
  'Magic'         => l10n.genreMagic,
  'Historical'    => l10n.genreHistorical,
  'Music'         => l10n.genreMusic,
  'Cooking'       => l10n.genreCooking,
  'Game'          => l10n.genreGame,
  'Ecchi'         => l10n.genreEcchi,
  'Harem'         => l10n.genreHarem,
  'Shonen'        => l10n.genreShonen,
  'Shojo'         => l10n.genreShojo,
  'Seinen'        => l10n.genreSeinen,
  'Josei'         => l10n.genreJosei,
  'Kodomomuke'    => l10n.genreKodomomuke,
  'Yaoi'          => l10n.genreYaoi,
  'Yuri'          => l10n.genreYuri,
  'Gore'          => l10n.genreGore,
  'Military'      => l10n.genreMilitary,
  'Politics'      => l10n.genrePolitics,
  _               => genre,
};

const List<String> tousLesGenres = [
  'Action',
  'Adventure',
  'Martial Arts',
  'Sports',
  'Romance',
  'Comedy',
  'Drama',
  'Slice of Life',
  'Mystery',
  'Thriller',
  'Horror',
  'Psychological',
  'Fantasy',
  'Sci-Fi',
  'Isekai',
  'Supernatural',
  'Mecha',
  'Magic',
  'Historical',
  'Music',
  'Cooking',
  'Game',
  'Ecchi',
  'Harem',
  'Shonen',
  'Shojo',
  'Seinen',
  'Josei',
  'Kodomomuke',
  'Yaoi',
  'Yuri',
  'Gore',
  'Military',
  'Politics',
];
